task_job:
    resource: "@TaskBundle/Resources/config/routing/job.yml"
    prefix:   /job

about:
    path:     /about
    defaults: { _controller: "TaskBundle:Home:about" }

help:
    path:     /help
    defaults: { _controller: "TaskBundle:Home:help" }
    