task_job:
    resource: "@TaskBundle/Resources/config/routing/job.yml"
    prefix:   /job

about:
    path:     /about
    defaults: { _controller: task.home_controller:about }

help:
    path:     /help
    defaults: { _controller: task.home_controller:help }
    