services:    
    job_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - TaskBundle\Entity\Job         
            
    request:
        class: Symfony\Component\HttpFoundation\Request

    filter_chain_request:
        class: TaskBundle\FilterChain\FilterChainRequest
           
    task.job_controller:
        class: TaskBundle\Controller\JobController
        arguments:   
            - @templating
            - @request
            - @filter_chain_request
            - @job_repository

    task.home_controller:
        class: TaskBundle\Controller\HomeController
        arguments:   
            - @templating

    job_board.mailer:
        class: TaskBundle\Mailer\JobBoardMailer
        arguments:   
            - @swiftmailer.mailer.default

    listener.job_mail:
        class: TaskBundle\Listener\JobEmailListener
        arguments:   
            - @job_board.mailer
            - @templating
        tags:
            - { name: kernel.event_listener, event: job.created, method: onJobCreated }            
        
